// Generated by gencpp from file rtabmap_ros/AddLink.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_ADDLINK_H
#define RTABMAP_ROS_MESSAGE_ADDLINK_H

#include <ros/service_traits.h>


#include <rtabmap_ros/AddLinkRequest.h>
#include <rtabmap_ros/AddLinkResponse.h>


namespace rtabmap_ros
{

struct AddLink
{

typedef AddLinkRequest Request;
typedef AddLinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddLink
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::AddLink > {
  static const char* value()
  {
    return "050728e3c25a15bf78d487d6aafab152";
  }

  static const char* value(const ::rtabmap_ros::AddLink&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::AddLink > {
  static const char* value()
  {
    return "rtabmap_ros/AddLink";
  }

  static const char* value(const ::rtabmap_ros::AddLink&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::AddLinkRequest> should match
// service_traits::MD5Sum< ::rtabmap_ros::AddLink >
template<>
struct MD5Sum< ::rtabmap_ros::AddLinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::AddLink >::value();
  }
  static const char* value(const ::rtabmap_ros::AddLinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::AddLinkRequest> should match
// service_traits::DataType< ::rtabmap_ros::AddLink >
template<>
struct DataType< ::rtabmap_ros::AddLinkRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::AddLink >::value();
  }
  static const char* value(const ::rtabmap_ros::AddLinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::AddLinkResponse> should match
// service_traits::MD5Sum< ::rtabmap_ros::AddLink >
template<>
struct MD5Sum< ::rtabmap_ros::AddLinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::AddLink >::value();
  }
  static const char* value(const ::rtabmap_ros::AddLinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::AddLinkResponse> should match
// service_traits::DataType< ::rtabmap_ros::AddLink >
template<>
struct DataType< ::rtabmap_ros::AddLinkResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::AddLink >::value();
  }
  static const char* value(const ::rtabmap_ros::AddLinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_ADDLINK_H
