// Generated by gencpp from file rtabmap_ros/GetMap2.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_GETMAP2_H
#define RTABMAP_ROS_MESSAGE_GETMAP2_H

#include <ros/service_traits.h>


#include <rtabmap_ros/GetMap2Request.h>
#include <rtabmap_ros/GetMap2Response.h>


namespace rtabmap_ros
{

struct GetMap2
{

typedef GetMap2Request Request;
typedef GetMap2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap2
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::GetMap2 > {
  static const char* value()
  {
    return "69c0119b3ce4329b231c2f8b1b1d38f8";
  }

  static const char* value(const ::rtabmap_ros::GetMap2&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::GetMap2 > {
  static const char* value()
  {
    return "rtabmap_ros/GetMap2";
  }

  static const char* value(const ::rtabmap_ros::GetMap2&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::GetMap2Request> should match
// service_traits::MD5Sum< ::rtabmap_ros::GetMap2 >
template<>
struct MD5Sum< ::rtabmap_ros::GetMap2Request>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::GetMap2 >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMap2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::GetMap2Request> should match
// service_traits::DataType< ::rtabmap_ros::GetMap2 >
template<>
struct DataType< ::rtabmap_ros::GetMap2Request>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::GetMap2 >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMap2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::GetMap2Response> should match
// service_traits::MD5Sum< ::rtabmap_ros::GetMap2 >
template<>
struct MD5Sum< ::rtabmap_ros::GetMap2Response>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::GetMap2 >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMap2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::GetMap2Response> should match
// service_traits::DataType< ::rtabmap_ros::GetMap2 >
template<>
struct DataType< ::rtabmap_ros::GetMap2Response>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::GetMap2 >::value();
  }
  static const char* value(const ::rtabmap_ros::GetMap2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_GETMAP2_H
